
[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = "3.3.1"

[[constraint]]
  name = "go.uber.org/cadence"
  version = "0.8.5"

[[constraint]]
  name = "go.uber.org/yarpc"
  version = "1.29.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[override]]
  name = "github.com/apache/thrift"
  #packages = ["lib/go/thrift"]
  revision = "9549b25c77587b29be4e0b5c258221a4ed85d37a"

[prune]
  go-tests = true
  unused-packages = true